[workspace]
resolver = "2"
members = [
	"crates/*",
	"tasks/*",
]

[workspace.package]
authors = ["Boshen <boshenc@gmail.com>"]
description = "The JavaScript Oxidation Compiler"
edition = "2021"
homepage = "https://github.com/Boshen/oxc"
keywords = ["JavaScript", "TypeScript", "compiler", "parser"]
license = "MIT"
repository = "https://github.com/Boshen/oxc"
version = "0.0.0"

[workspace.dependencies]
bitflags = "1.3.2"
bumpalo = "3.12.0"
compact_str = "0.6.1"
miette = "5.5.0"
rayon = "1.6.1"
rustc-hash = "1.1.0"
serde = "1.0.152"
serde_json = "1.0.93"
thiserror = "1.0.38"
jemallocator = "0.5.0"
clap = "4.1.4"

[profile.release]
lto = "fat"
codegen-units = 1
strip = true

# DO NOT SET PANIC TO ABORT
# we are using catch_unwind for panic recovery
panic = "unwind"
