[package]
name = "oxc_linter"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
oxc_ast = { path = "../oxc_ast" }
oxc_diagnostics = { path = "../oxc_diagnostics" }
oxc_semantic = { path = "../oxc_semantic" }

[dev_dependencies]
insta = { version = "1.14.0", features = ["glob"] }
oxc_allocator = { path = "../oxc_allocator" }
oxc_parser = { path  = "../oxc_parser" }
miette = { workspace = true, features = ["fancy"] }
