[package]
name = "oxc_cli"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
mimalloc = { workspace = true }

[dependencies]
oxc_diagnostics = { path = "../oxc_diagnostics" }
oxc_allocator = { path = "../oxc_allocator" }
oxc_ast = { path  = "../oxc_ast" }
oxc_parser = { path  = "../oxc_parser" }
oxc_semantic = { path  = "../oxc_semantic" }
oxc_linter = { path  = "../oxc_linter" }

clap = { workspace = true }
glob = { workspace = true }
rayon = { workspace = true }
miette = { workspace = true, features = ["fancy"] }

ignore = "0.4.20"
git2 = "0.16.1"
