[package]
name = "oxc_semantic"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
oxc_ast = { path = "../oxc_ast" }

indextree = { workspace = true }
bitflags = { workspace = true }
