[package]
name = "oxc_benchmark"
publish = false
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
oxc_ast = { path = "../../crates/oxc_ast" }
oxc_allocator = { path = "../../crates/oxc_allocator" }
oxc_parser = { path = "../../crates/oxc_parser" }

pico-args = "0.5.0"
criterion = { version = "0.4.0", default-features = false }
ureq = "2.6.2"
url = "2.3.1"
